import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import HeroSection from "../components/Landing/HeroSection";
import TierSection from "../components/Landing/TierSection";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>ProfitSaloon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <HeroSection />
        <TierSection />
      </main>
    </>
  );
};

export default Home;
